In [6]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
Y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X, axis=0)
actual_output = Y / 100
print(X)
print(actual_output)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [7]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

In [8]:
epoch = 1000
learning_rate = 0.15
inputlayer_neurons = 2
hiddenlayer_neurons = 3
outputlayer_neurons = 1

# Weight of hidden layer
wh = np.random.uniform(low=-0.05,high=0.05,size=(inputlayer_neurons, hiddenlayer_neurons))

# Bias of hidden layer
bh = np.random.uniform(low=-0.05,high=0.05,size=(1, hiddenlayer_neurons))

# Weight of output layer
wo = np.random.uniform(low=-0.05,high=0.05, size=(hiddenlayer_neurons, outputlayer_neurons))

# Bias of output layer
bo = np.random.uniform(low=-0.05,high=0.05,size=(1, outputlayer_neurons))

In [11]:
# training
for i in range(epoch):
    net_h = np.dot(X, wh) + bh
    sigma_h = sigmoid(net_h)
    net_o = np.dot(sigma_h, wo) + bo
    output = sigmoid(net_o)
    
 #Backpropagation
 # Error at Output layer
    eo = actual_output-output # Error at o/p
    outgrad = derivatives_sigmoid(output)
    d_output = eo* outgrad

# Error at Hidden later
    eh = d_output.dot(wo.T) 
    hiddengrad = derivatives_sigmoid(sigma_h) 
    d_hidden = eh * hiddengrad
    wo += sigma_h.T.dot(d_output) *learning_rate 
    wh += X.T.dot(d_hidden) *learning_rate
    sum_error = 0
    
    for j in range(len(actual_output)):
        print(output[j],actual_output[j] )
        sum_error+=((output[j] - actual_output[j])**2)
        
    sum_error /=2
    print(f'Epoch {i} error {sum_error}')



In [10]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(actual_output))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89560827]
 [0.87960006]
 [0.89473688]]
